config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :reservations, except: :show
  resources :buildings, only: [:index, :show] do
    resources :classrooms, only: [:show]
  end

  namespace 'qr' do
    resources :buildings, only: [:index, :show] do
      resources :classrooms, only: [:show]
    end
  end

  namespace 'admin' do
    resources :dashboard
    resources :buildings do
      resources :classrooms do
        resources :devices
        resources :options
      end
    end
    resources :options, except: :show
    resources :devices, only: [:index, :edit, :update, :destroy]
    resources :users
  end

  namespace 'api' do
    namespace 'v1' do
      resources :reservations
      resources :buildings do
        resources :classrooms
      end
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks], controllers: {
          token_validations: 'overrides/token_validations',
          sessions: 'overrides/sessions'
      }
    end

    namespace 'v2' do
      resources :devices, only: [:update]
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminController

end

app/views/admin/dashboard/index.html.erb
<div class="breadcrumbs">
  <%= link_to 'Administrator Dashboard', admin_dashboard_index_path %>
</div>
<div class="container">
  <%= link_to admin_buildings_path do %>
    <div class="admin_button">
      <%= image_tag("building_icon.png") %><br />
      <%= link_to 'Manage buildings', admin_buildings_path %>
    </div>
  <% end %>

  <%= link_to admin_options_path do %>
    <div class="admin_button">
      <%= image_tag("classroom_options_icon.png") %><br />
      <%= link_to 'Manage classroom options', admin_options_path %>
    </div>
  <% end %>

  <!--
  <%= link_to admin_devices_path do %>
    <div class="admin_button">
      <%= image_tag("devices_icon.png") %><br />
      <%= link_to 'Manage devices', admin_devices_path %>
    </div>
  <% end %>
  -->
  
  <%= link_to admin_users_path do %>
    <div class="admin_button">
      <%= image_tag("users_icon.png") %><br />
      <%= link_to 'Manage users', admin_users_path %>
    </div>
  <% end %>
</div>