config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :reservations, except: :show
  resources :buildings, only: [:index, :show] do
    resources :classrooms, only: [:show]
  end

  namespace 'qr' do
    resources :buildings, only: [:index, :show] do
      resources :classrooms, only: [:show]
    end
  end

  namespace 'admin' do
    resources :dashboard
    resources :buildings do
      resources :classrooms do
        resources :devices
        resources :options
      end
    end
    resources :options, except: :show
    resources :devices, only: [:index, :edit, :update, :destroy]
    resources :users
  end

  namespace 'api' do
    namespace 'v1' do
      resources :reservations
      resources :buildings do
        resources :classrooms
      end
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks], controllers: {
          token_validations: 'overrides/token_validations',
          sessions: 'overrides/sessions'
      }
    end

    namespace 'v2' do
      resources :devices, only: [:update]
    end
  end
end

app/models/classroom.rb
class Classroom < ApplicationRecord
	belongs_to :building
	has_one :device, dependent: :destroy
	has_many :reservations, dependent: :destroy
	has_and_belongs_to_many :options, dependent: :destroy

	# Must have fields
	validates :name, :max_persons, presence: true
end

app/controllers/admin/classrooms_controller.rb
class Admin::ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]
  before_action :set_building

  # GET /admin/classrooms
  def index
    @classrooms = Classroom.all
  end

  # GET /admin//classrooms/index
  def show
	  @reservation = Reservation.new
  end

  # GET /admin//classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /admin//classrooms/index/edit
  def edit
  end

  # POST /admin//classrooms
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @building.classrooms << @classroom
        format.html { redirect_to admin_building_path(@building), notice: 'Classroom was successfully created.' }
      else
        format.html { redirect_to new_admin_building_classroom_path(@building, @classroom), notice: 'Please fill in all the fields' }
      end
    end
  end

  # PUT /admin//classrooms/index
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to admin_building_path(@building), notice: 'Classroom was successfully updated.' }
      else
        format.html { redirect_to edit_admin_building_classroom_path(@building, @classroom), notice: 'Please fill in all the fields' }
      end
    end
  end

  # DELETE /classrooms/index
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to admin_building_path(@building), notice: "Classroom #{@classroom.name} was successfully deleted." }
    end
  end

  private
    # Callbacks
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def set_building
      @building = Building.find(params[:building_id])
    end

    # Trusted parameters
    def classroom_params
      params.require(:classroom).permit(:name, :max_persons, :option_ids => [])
    end
end

app/controllers/api/v1/classrooms_controller.rb
class Api::V1::ClassroomsController < ApiController

  # GET /api/v1/classrooms
  def index
    @classrooms = Classroom.where(building_id: params[:building_id])

    render "/api/v1/classrooms/index.json"
  end

  def show
    @classroom = Classroom.where(id: params[:id])

    render "/api/v1/classrooms/show.json"
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/index
  def show
	  @reservation = Reservation.new
    @reservations = Reservation.where(classroom_id: params[:id])
  end

  private
    # Callbacks
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end
end

app/controllers/qr/classrooms_controller.rb
class Qr::ClassroomsController < QrController

  # GET classrooms/index
  def show
    @classroom = Classroom.find(params[:id])
  end

end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
	def buildings_for_select
		Building.all.collect { |building| [building.name, building.id] }
	end
	
	def generate_qr(text)
		require 'barby'
		require 'barby/barcode'
		require 'barby/barcode/qr_code'
		require 'barby/outputter/png_outputter'

		barcode = Barby::QrCode.new(text, level: :q, size: 5)
		base64_output = Base64.encode64(barcode.to_png({ xdim: 5 }))
		"data:image/png;base64,#{base64_output}"
	end

	def current_week
		date = Date.today.beginning_of_week
		return (date..date + 4.days).to_a
	end

	def next_week
		date = Date.today.beginning_of_week + 7.days
		return (date..date + 4.days).to_a
	end

	def get_hours(block)
		case block
		when 1
			return "8:30 - 9:20"
		when 2
			return "9:20 - 10:10"
		when 3
			return "10:30 - 11:20"
		when 4
			return "11:20 - 12:10"
		when 5
			return "12:10 - 13:00"
		when 6
			return "13:00 - 13:50"
		when 7
			return "13:50 - 14:40"
		when 8
			return "15:00 - 15:50"
		when 9
			return "15:50 - 16:40"
		when 10
			return "17:00 - 17:50"
		when 11
			return "17:50 - 18:40"
		when 12
			return "18:40 - 19:30"
		when 13
			return "19:30 - 20:20"
		when 14
			return "20:20 - 21:10"
		when 15
			return "21:10 - 22:00"
		else
			return "Out of range"
		end
	end

	def get_start_hours(block)
		case block
		when 1
			return "8:30"
		when 2
			return "9:20"
		when 3
			return "10:30"
		when 4
			return "11:20"
		when 5
			return "12:10"
		when 6
			return "13:00"
		when 7
			return "13:50"
		when 8
			return "15:00"
		when 9
			return "15:50"
		when 10
			return "17:00"
		when 11
			return "17:50"
		when 12
			return "18:40"
		when 13
			return "19:30"
		when 14
			return "20:20"
		when 15
			return "21:10"
		else
			return "Out of range"
		end
	end

	def get_end_hours(block)
		case block
		when 1
			return "9:20"
		when 2
			return "10:10"
		when 3
			return "11:20"
		when 4
			return "12:10"
		when 5
			return "13:00"
		when 6
			return "13:50"
		when 7
			return "14:40"
		when 8
			return "15:50"
		when 9
			return "16:40"
		when 10
			return "17:50"
		when 11
			return "18:40"
		when 12
			return "19:30"
		when 13
			return "20:20"
		when 14
			return "21:10"
		when 15
			return "22:00"
		else
			return "Out of range"
		end
	end

	def get_reservation(date, hour)
		reservations = Reservation.where(classroom_id: params[:id], date: date)
		if reservations.length == 0
			return no_reservation(date, hour)
		elsif check_reservation(reservations, hour) != ''
			return check_reservation(reservations, hour)
		else
			return no_reservation(date, hour)
		end
	end

	def no_reservation(date, hour)
		return "<div onclick='showReservationForm(this)' class='dayHour empty' data-date-type='#{date}' data-block-type='#{hour}'>None</div>"
	end

	def check_reservation(reservations, hour)
		reservationString = ''
		reservations.each do |reservation|
			if (hour..hour).overlaps?(reservation.from_block..reservation.to_block)
				if reservation.from_block == hour
					reservationString = "<div class='dayHour start #{is_my_reservation(reservation.user_id)}'>#{is_my_or_admin_reservation(reservation.user_id, reservation)} #{reservation.title}<br />#{reservation.description}<br />#{reservation.user.try(:email)}</div>"
				elsif reservation.to_block == hour
					reservationString = "<div class='dayHour end #{is_my_reservation(reservation.user_id)}'> <br /></div>"
				else
					reservationString = "<div class='dayHour busy #{is_my_reservation(reservation.user_id)}'> <br /></div>"
				end
			end
		end
		return reservationString
	end

	def is_my_or_admin_reservation(user_id, reservation)
			if current_user && (current_user.id == user_id || current_user.role == 2)
				return link_to reservation_path(reservation), method: :delete, data: { confirm: 'Are you sure?' } do
            image_tag "delete.png", class: "action"
				end
			end
	end

	def is_my_reservation(user_id)
		if current_user && current_user.id == user_id
			return 'myReservation'
		end
	end

	def get_availability(classroom)
		block = get_current_block
		reservation = Reservation.where("classroom_id = ? AND from_block <= ? AND to_block >= ? AND date = ?", classroom.id, block, block, Time.now.strftime("%Y-%m-%d"))
		if reservation.length == 0
			return '<div class="classroomFree">Currently free</div>'
		else
			return '<div class="classroomTaken">Currently taken</div>'
		end
	end

	def get_current_block
		hour = Time.now.hour
		minutes = Time.now.min
		time = hour*100 + minutes

		case time
		when 830..920
			return 1
		when 920..1010
			return 2
		when 1010..1120
			return 3
		when 1120..1210
			return 4
		when 1210..1300
			return 5
		when 1300..1350
			return 6
		when 1350..1440
			return 7
		when 1440..1550
			return 8
		when 1550..1640
			return 9
		when 1700..1750
			return 10
		when 1750..1840
			return 11
		when 1840..1930
			return 12
		when 1930..2020
			return 13
		when 2020..2110
			return 14
		when 2110..2200
			return 15
		else
			return 1
		end
	end

end

app/views/admin/classrooms/_form.html.erb
<%= form_for [:admin, @building, @classroom] do |form| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :classroom_name %>
  </div>

  <div class="field">
    <%= form.label :maximum_persons %>
    <%= form.number_field :max_persons, id: :classroom_max_persons %>
  </div>

  <div class="horizontalField">
    <%= form.label :options %><br />
    <%= Option.all.length == 0 ? 'None' : form.collection_check_boxes(:option_ids, Option.all, :id, :name_with_initial) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/classrooms/_reservation_form.html.erb
<div class="reservationFormBg">
  <div class="reservationForm" id="reservationForm">
    <div class="hideReservationForm" onclick="hideReservationForm()">&#10006</div>
    <h1>Create a reservation</h1>
    <%= form_with(model: reservation, local: true) do |form| %>
      <% if reservation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being booked:</h2>

          <ul>
            <% reservation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field" style='display: none;'>
        <%= form.label :classroom_id %>
        <%= form.text_field :classroom_id, id: :classroom_id, value: params[:id] %>
      </div>

      <div class="field">
        <%= form.label :date %>
        <%= form.text_field :date, data:{ provide:'datepicker' }, id: :reservation_date %>
      </div>

      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, id: :reservation_title %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_field :description, id: :reservation_description %>
      </div>

      <div class="field">
        <%= form.label :from_block %>
        <%= form.text_field :from_block, id: :reservation_from_block %>
      </div>

      <div class="field">
        <%= form.label :to_block %>
        <%= form.text_field :to_block, id: :reservation_to_block %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/classrooms/edit.html.erb
<% if notice %>
  <div class="error">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @building.name, admin_building_path(@building) %>
  <span> / </span>
  <%= link_to 'Edit ' + @classroom.name, edit_admin_building_classroom_path(@building, @classroom) %>
</div>

<div class="formContainer">
  <h1>Editing classroom <%= @classroom.name %> for <%= @building.name %></h1>

  <%= render 'form', classroom: @classroom %>

  <%= link_to admin_building_path(@building) do %>
    <div class="backButton">
      <p>Back</p>
    </div>
  <% end %>
</div>

app/views/admin/classrooms/index.html.erb
<% if notice %>
  <div class="success">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @building.name, admin_building_path(@building) %>
  <span> / </span>
  <%= link_to 'Classrooms', admin_building_classrooms_path %>
</div>

<div class="classroomContainer">
  <% @classrooms.each do |classroom| %>
    <%= link_to admin_building_classroom_path(classroom.building, classroom) do %>
      <div class="classroomBox">
        <div class="classroomHeader">
          <span class="title"><%= classroom.name %></span>
          <span class="description"><%= classroom.building.name %></span>
        </div>
        <div class="classroomFree">
          <p>Free until 14:30</p>
        </div>
        <div class="classroomContent">
          <p><%= classroom.options.map { |option| option.name }.join(', ').html_safe %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to admin_building_path(@building) do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>

app/views/admin/classrooms/new.html.erb
<% if notice %>
<div class="error">
  <p><%= notice %></p>
</div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @building.name, admin_building_path(@building) %>
  <span> / </span>
  <%= link_to 'New classroom ', new_admin_building_classroom_path(@building) %>
</div>

<div class="formContainer">
  <h1>Create a new classroom for <%= @building.name %></h1>

  <%= render 'form', classroom: @classroom %>

  <%= link_to admin_building_path(@building) do %>
    <div class="backButton">
      <p>Back</p>
    </div>
  <% end %>
</div>

app/views/admin/classrooms/show.html.erb
<% if notice %>
  <div class="success">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @building.name, admin_building_path(@building) %>
  <span> / </span>
  <%= link_to 'Classrooms', admin_building_classrooms_path %>
  <span> / </span>
  <%= link_to @classroom.name, admin_building_classroom_path(@classroom) %>
</div>

<p>
  <strong>Building:</strong>
  <%= @classroom.building.name %><br />

  <strong>Name:</strong>
  <%= @classroom.name %><br />

  <strong>Temperature:</strong>
  <%= @classroom.try(:device).try(:temperature).nil? ? 'None' : @classroom.try(:device).try(:temperature) %><br />

  <strong>Humidity:</strong>
  <%= @classroom.try(:device).try(:humidity).nil? ? 'None' : @classroom.try(:device).try(:humidity) %><br />

  <% if @classroom.device %>
    <strong>Device:</strong>
    <%= @classroom.device.id %> <%= @classroom.device.name %>,

    <strong>Device token:</strong>
    <%= @classroom.device.auth %>

    <%= link_to edit_admin_building_classroom_device_path(@building, @classroom, @classroom.device) do %>
      <%= image_tag "edit.png", class: "action" %>
    <% end %>

    <%= link_to admin_building_classroom_device_path(@building, @classroom, @classroom.device), method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= image_tag "delete.png", class: "action" %>
    <% end %>

  <% else %>
    <strong>Create new device:</strong>
    <%= link_to 'New device', new_admin_building_classroom_device_path(@classroom.building, @classroom) %>
  <% end %>
</p>

<div class="classroomReservationContainer">
  <div class="calendar">
    <div class="dayColumn">
      <div class="dayHeader">
        &nbsp;<br />&nbsp;
      </div>
      <% (1..15).each do |block| %>
        <div class="dayHourText"><%= block %>: <%= get_hours(block) %></div>
      <% end %>
    </div>
    <% current_week.each do |date| %>
      <div class="dayColumn">
        <div class="dayHeader">
          <%= date.strftime("%A")%><br />
          <%= date %>
        </div>
        <% (1..15).each do |hour| %>
          <%= get_reservation(date, hour).html_safe %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="reservation">
    <%= render 'reservation_form', reservation: @reservation %>
  </div>
</div>

<%= link_to admin_building_classrooms_path do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>