config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :reservations, except: :show
  resources :buildings, only: [:index, :show] do
    resources :classrooms, only: [:show]
  end

  namespace 'qr' do
    resources :buildings, only: [:index, :show] do
      resources :classrooms, only: [:show]
    end
  end

  namespace 'admin' do
    resources :dashboard
    resources :buildings do
      resources :classrooms do
        resources :devices
        resources :options
      end
    end
    resources :options, except: :show
    resources :devices, only: [:index, :edit, :update, :destroy]
    resources :users
  end

  namespace 'api' do
    namespace 'v1' do
      resources :reservations
      resources :buildings do
        resources :classrooms
      end
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks], controllers: {
          token_validations: 'overrides/token_validations',
          sessions: 'overrides/sessions'
      }
    end

    namespace 'v2' do
      resources :devices, only: [:update]
    end
  end
end

app/models/device.rb
class Device < ApplicationRecord
	belongs_to :classroom

	# Must have fields
	validates :name, presence: true
end

app/controllers/admin/devices_controller.rb
class Admin::DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :set_classroom, only: [:new, :edit, :create, :update]

  # GET /admin/devices
  def index
    @devices = Device.all
  end

  # GET /admin/devices/index
  def show
  end

  # GET /admin/devices/new
  def new
    @device = Device.new
  end

  # GET /admin/devices/index/edit
  def edit
  end

  # POST /admin/devices
  def create
    @device = Device.new(device_params)
    @device.classroom_id = @classroom.id
    respond_to do |format|
      if @device.save
        format.html { redirect_to admin_building_classroom_path(@device.classroom.building, @device.classroom) , notice: 'Device was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PUT /admin/devices/index
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to admin_building_classroom_path(@device.classroom.building, @device.classroom), notice: 'Device was successfully updated.' }
      else
        format.html { render "admin/buildings/#{@classroom.building.id}/classrooms/#{@classroom.id}/devices/#{@device.id}/edit" }
      end
    end
  end

  # DELETE /admin/devices/index
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to admin_building_classroom_path(@device.classroom.building, @device.classroom), notice: 'Device was successfully deleted.' }
    end
  end

  private
    # Callbacks
    def set_device
      @device = Device.find(params[:id])
    end

    def set_classroom
      @classroom = Classroom.find(params[:classroom_id])
    end

    # Trusted parameters
    def device_params
      params.require(:device).permit(:name, :auth)
    end
end

app/controllers/api/v2/devices_controller.rb
class Api::V2::DevicesController < ApplicationController
  before_action :set_device

  # PUT /api/v2/devices/index
  def update
    if @device.auth == params[:auth]
        if @device.update(device_params)
          render json: {
              success: true
          }, status: 200
        else
          render json: {
              success: false,
              errors: @device.errors
          }, status: :unprocessable_entity
        end
    else
      render json: {
          success: false,
          errors: ["Unauthorized"]
      }, status: 401
    end
  end

  private
  # Callbacks
  def set_device
    @device = Device.find(params[:id])
  end

  # Trusted parameters
  def device_params
    params.require(:device).permit(:auth, :temperature, :humidity)
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
	def classrooms_for_select
	  Classroom.where(building_id: params[:id]).order(:name).collect { |classroom| [classroom.name, classroom.id] }
	end
end

app/views/admin/devices/_form.html.erb
<%= form_for [:admin, @classroom.building, @classroom, @device] do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :device_name %>
  </div>

  <div class="field">
    <%= form.label :authentication_token %>
    <%= form.text_field :auth, id: :device_auth %>
    <div id="generateAuth" class="generateButton" onClick="generateToken();">Generate token</div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/devices/_form_edit.html.erb
<%= form_for [:admin, @building, @classroom, @device] do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :device_name %>
  </div>

  <div class="field">
    <%= form.label :authentication_token %>
    <%= form.text_field :auth, id: :device_auth %>
    <div id="generateAuth" class="generateButton" onClick="generateToken();">Generate token</div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/devices/_form_new.html.erb
<%= form_for [:admin, @classroom.building, @classroom, @device] do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :device_name %>
  </div>

  <div class="field">
    <%= form.label :authentication_token %>
    <%= form.text_field :auth, id: :device_auth %>
    <div id="generateAuth" class="generateButton" onClick="generateToken();">Generate token</div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/devices/edit.html.erb
<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @classroom.building.name, admin_building_path(@classroom.building) %>
  <span> / </span>
  <%= link_to 'Classrooms', admin_building_classrooms_path %>
  <span> / </span>
  <%= link_to @classroom.name, admin_building_classroom_path(@classroom.building, @classroom) %>
  <span> / </span>
  <%= link_to "Edit device", new_admin_building_classroom_device_path(@classroom.building, @classroom, @device) %>
</div>

<div class="formContainer">
  <h1>Editing device <%= @device.name %></h1>

  <%= render 'form', device: @device %>

  <%= link_to admin_building_classroom_path(@device.classroom.building, @device.classroom) do %>
    <div class="backButton">
      <p>Back</p>
    </div>
  <% end %>
</div>

app/views/admin/devices/index.html.erb
<% if notice %>
  <div class="success">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <%= link_to 'Administrator Dashboard', admin_dashboard_index_path %>
  <span> / </span>
  <%= link_to 'Devices', admin_devices_path %>
</div>

<table class="adminTable">
  <thead>
    <tr>
      <td>Id</td>
      <td>Building</td>
      <td>Classroom</td>
      <td>Device name</td>
      <td>Temperature</td>
      <td>Humidity</td>
      <td>Authentication token</td>
      <td>Action</td>
    </tr>
  </thead>
  <% @devices.each do |device| %>
      <tr>
        <td><%= device.id %></td>
        <td><%= device.try(:classroom).try(:building).try(:name) %></td>
        <td><%= device.try(:classroom).try(:name) %></td>
        <td><%= device.name %></td>
        <td><%= device.temperature %></td>
        <td><%= device.humidity %></td>
        <td><%= device.auth %></td>
        <td>

          <%= link_to admin_device_path(device), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= image_tag "delete.png", class: "action" %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

<%= link_to 'dashboard' do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>

app/views/admin/devices/new.html.erb
<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @classroom.building.name, admin_building_path(@classroom.building) %>
  <span> / </span>
  <%= link_to 'Classrooms', admin_building_classrooms_path %>
  <span> / </span>
  <%= link_to @classroom.name, admin_building_classroom_path(@classroom.building, @classroom) %>
  <span> / </span>
  <%= link_to "New device", new_admin_building_classroom_device_path(@classroom.building, @classroom, @device) %>
</div>

<div class="formContainer">
  <h1>New device for <%= @classroom.name %> in <%= @classroom.building.name %></h1>

  <%= render 'form', device: @device %>

</div>

app/views/admin/devices/show.html.erb
<% if notice %>
  <div class="success">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Devices', admin_devices_path %>
  <span> / </span>
  <%= link_to @device.name, request.original_url %>
</div>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<p>
  <strong>Temperature:</strong>
  <%= @device.temperature %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>