config/routes.rb
Rails.application.routes.draw do
  root 'buildings#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :reservations, except: :show
  resources :buildings, only: [:index, :show] do
    resources :classrooms, only: [:show]
  end

  namespace 'qr' do
    resources :buildings, only: [:index, :show] do
      resources :classrooms, only: [:show]
    end
  end

  namespace 'admin' do
    resources :dashboard
    resources :buildings do
      resources :classrooms do
        resources :devices
        resources :options
      end
    end
    resources :options, except: :show
    resources :devices, only: [:index, :edit, :update, :destroy]
    resources :users
  end

  namespace 'api' do
    namespace 'v1' do
      resources :reservations
      resources :buildings do
        resources :classrooms
      end
      mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks], controllers: {
          token_validations: 'overrides/token_validations',
          sessions: 'overrides/sessions'
      }
    end

    namespace 'v2' do
      resources :devices, only: [:update]
    end
  end
end

app/models/building.rb
class Building < ApplicationRecord
	has_many :classrooms, dependent: :destroy

	# Must have fields
	validates :name, presence: true
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  # GET /admin/buildings
  def index
    @buildings = Building.all
  end

  # GET /admin/buildings/index
  def show
  end

  # GET /admin/buildings/new
  def new
    @building = Building.new
  end

  # GET /admin/buildings/index/edit
  def edit
  end

  # POST /admin/buildings
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to admin_buildings_path, notice: 'Building was successfully created.' }
      else
        format.html { render new_admin_building_path }
      end
    end
  end

  # PUT /admin/buildings/index
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to admin_buildings_path, notice: 'Building was successfully updated.' }
      else
        format.html { render new_admin_building_path }
      end
    end
  end

  # DELETE /admin/buildings/index
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to admin_buildings_path, notice: 'Building was successfully deleted.' }
    end
  end

  private
  # Callbacks
  def set_building
    @building = Building.find(params[:id])
  end

  # Trusted parameters
  def building_params
    params.require(:building).permit(:name)
  end
end

app/controllers/api/v1/buildings_controller.rb
class Api::V1::BuildingsController < ApiController

  # GET /api/v1/buildings
  def index
    @buildings = Building.all

    render "/api/v1/buildings/index.json"
  end

  def show

  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: :show

  # GET /buildings
  def index
    @buildings = Building.all
  end

  # GET /buildings/index
  def show
  end

  private
  # Callbacks
  def set_building
    @building = Building.find(params[:id])
  end
end

app/controllers/qr/buildings_controller.rb
class Qr::BuildingsController < QrController

  # GET buildings
  def index
    @buildings = Building.all
  end

  # GET buildings/index
  def show
    @building = Building.find(params[:id])
  end

end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/admin/buildings/_form.html.erb
<%= form_for [:admin, @building] do |form| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :building_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/buildings/edit.html.erb
<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to 'Edit ' + @building.name, edit_admin_building_path(@building) %>
</div>

<div class="formContainer">
  <h1>Edit <%= @building.name %></h1>

  <%= render 'form', building: @building %>

</div>

<%= link_to admin_buildings_path do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>

app/views/admin/buildings/index.html.erb
<% if notice %>
  <div class="success">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
</div>

<table class="adminTable">
  <thead>
    <tr>
      <td>Id</td>
      <td>Building name</td>
      <td>Action</td>
    </tr>
  </thead>

    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.id %></td>
        <td><%= building.name %></td>
        <td>
          <%= link_to admin_building_path(building) do %>
            <%= image_tag "show.png", class: "action" %>
          <% end %>

          <%= link_to edit_admin_building_path(building) do %>
            <%= image_tag "edit.png", class: "action" %>
          <% end %>

          <%= link_to admin_building_path(building), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= image_tag "delete.png", class: "action" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td colspan="3">
        <%= link_to new_admin_building_path do %>
          <%= image_tag "add.png", class: "action" %><span class="noLink"> Add a new building</span>
        <% end %>
      </td>
    </tr>
</table>

<%= link_to 'dashboard' do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>

app/views/admin/buildings/new.html.erb
<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to 'New building', new_admin_building_path %>
</div>

<div class="formContainer">
  <h1>Create a new building</h1>

  <%= render 'form', building: @building %>

</div>

<%= link_to admin_buildings_path do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>

app/views/admin/buildings/show.html.erb
<% if notice %>
  <div class="success">
    <p><%= notice %></p>
  </div>
<% end %>

<div class="breadcrumbs">
  <a href="/admin/dashboard">Administrator Dashboard</a>
  <span> / </span>
  <%= link_to 'Buildings', admin_buildings_path %>
  <span> / </span>
  <%= link_to @building.name, request.original_url %>
</div>

<p>
  <strong>Location:</strong>
  <span><%= @building.name %></span>
  <%= link_to edit_admin_building_path(@building) do %>
    <%= image_tag "edit.png", class: "action" %>
  <% end %>
</p>

<table class="adminTable">
  <thead>
    <tr>
      <td>Classroom name</td>
      <td>Options</td>
      <td>Temperature</td>
      <td>Maximum persons</td>
      <td>Actions</td>
    </tr>
  </thead>

  <% @building.classrooms.each do |classroom| %>
    <tr>
      <td><%= classroom.name %></td>
      <td><%= classroom.options.length == 0 ? 'None' : classroom.options.map { |option| option.name }.join(', ').html_safe %></td>
      <td><%= classroom.try(:device).try(:temperature).nil? ? 'None' : classroom.try(:device).try(:temperature) %></td>
      <td><%= classroom.max_persons %></td>
      <td>
        <%= link_to admin_building_classroom_path(@building, classroom) do %>
          <%= image_tag "show.png", class: "action" %>
        <% end %>

        <%= link_to edit_admin_building_classroom_path(@building, classroom) do %>
          <%= image_tag "edit.png", class: "action" %>
        <% end %>

        <%= link_to admin_building_classroom_path(@building, classroom), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <%= image_tag "delete.png", class: "action" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  <tr>
    <td colspan="5">
      <%= link_to new_admin_building_classroom_path(@building) do %>
        <%= image_tag "add.png", class: "action" %><span class="noLink"> Add a new classroom</span>
      <% end %>
    </td>
  </tr>
</table>

<%= link_to admin_buildings_path do %>
  <div class="backButton">
    <p>Back</p>
  </div>
<% end %>